---
# tasks file for raspberry-gps
- name: Update packages list
  apt:
    update_cache: yes
- name: upgrade a server
  apt: 
    upgrade: dist
- name: Install required packages
  apt:
    name: "{{ packages }}"
    state: present
- name: Copy chronyc configuration files
  copy:
    src: chrony.conf
    dest: /etc/chrony/chrony.conf
    owner: root
    group: root
    mode: 0644
  notify:
    - restart chronyd
- name: Configure GPSD
  lineinfile:
    path: /etc/default/gpsd
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    - { regexp: '^DEVICES=', line: 'DEVICES="/dev/ttyUSB0"' }
    - { regexp: '^GPSD_OPTIONS=', line: 'GPSD_OPTIONS="-n -b"' }
  notify:
    - restart gpsd
- name: Copy gpslogger main script
  copy:
    src: gpslog.sh
    dest: /home/pirate/gpslog.sh
    owner: pirate
    group: pirate
    mode: 0755
  tags: debug
- name: Copy gpslogger systemd files
  copy:
    src: gpslogger.service
    dest: /etc/systemd/system/gpslogger.service
    owner: root
    group: root
    mode: 0644
  notify:
    - restart gpslogger
  tags: debug


- name: Check if a reboot is required
  register: file
  stat: path=/var/run/reboot-required get_md5=no
- name: Reboot the server
  command: /sbin/reboot
  when: file.stat.exists == true
